using System.Net;
using System.Text;
using System.Text.RegularExpressions;

namespace UeDtLauncher;

/// <summary>
/// Server-side per-project IP allowlist. Kept as a separate server-only file (NOT in the
/// client-facing catalog) because it is infrastructure access-control data.
/// Shape: { "projects": { "&lt;projectId&gt;": ["10.10.20.0/24", "172.18.45.7", ...] } }
/// </summary>
public sealed class ProjectIpAllowlist
{
    public Dictionary<string, List<string>> Projects { get; set; } = new();
}

/// <summary>
/// Turns a <see cref="ProjectIpAllowlist"/> into nginx per-project <c>location</c> blocks that
/// allow only the listed IPs/CIDRs and deny everyone else. nginx is the only real enforcement
/// point (the launcher runs on the client and can be bypassed).
/// </summary>
public static class NginxAclGenerator
{
    public static string Generate(ProjectIpAllowlist allowlist)
    {
        if (allowlist.Projects.Count == 0) throw new ArgumentException("Allowlist has no projects.");

        var sb = new StringBuilder();
        sb.AppendLine("# AUTO-GENERATED by 'UeDtLauncher generate-nginx-acl'. Do not edit by hand.");
        sb.AppendLine("# Per-project IP allowlist (서버 측 인프라 접근 제어).");
        sb.AppendLine("#");
        sb.AppendLine("# INCLUDE THIS AS THE FIRST regex location in the server block — ABOVE the");
        sb.AppendLine("# `~* \\.(json|sig)$` block AND the generic `^/projects/` blocks. Otherwise");
        sb.AppendLine("# manifest/catalog/.sig requests match those first and bypass this ACL.");
        sb.AppendLine("# (nginx는 소스 순서대로 정규식 location을 평가하고 첫 매칭이 이깁니다 —");
        sb.AppendLine("#  반드시 server 블록의 맨 위에 두세요.)");
        sb.AppendLine("#");
        sb.AppendLine("# Only the projects listed here are restricted. Projects NOT listed keep the normal");
        sb.AppendLine("# public/auth rules — they are NOT denied by default. To lock a project down it must");
        sb.AppendLine("# be listed here. (목록에 없는 프로젝트는 자동 차단되지 않습니다.)");
        sb.AppendLine("#");
        sb.AppendLine("# Each block gates the ENTIRE project path (prod + dev) to the listed IPs/CIDRs.");

        foreach (var (projectId, entries) in allowlist.Projects)
        {
            if (string.IsNullOrWhiteSpace(projectId)) throw new ArgumentException("Allowlist contains an empty projectId.");
            if (entries is null || entries.Count == 0) throw new ArgumentException($"Project '{projectId}' has no allowed IPs/CIDRs.");

            sb.AppendLine();
            sb.AppendLine($"location ~ ^/projects/{Regex.Escape(projectId)}/ {{");
            foreach (var entry in entries)
            {
                ValidateCidrOrIp(projectId, entry);
                if (IsAllAddresses(entry))
                {
                    Console.Error.WriteLine($"WARNING: project '{projectId}' allows {entry.Trim()} (everyone) — IP restriction has no effect.");
                }
                sb.AppendLine($"    allow {entry.Trim()};");
            }
            sb.AppendLine("    deny all;");
            // This per-project block now serves manifest/catalog/.sig for restricted projects
            // (it sits above the json/sig block), so keep those responses uncached.
            sb.AppendLine("    add_header Cache-Control \"no-cache\" always;");
            sb.AppendLine("    try_files $uri =404;");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>True if the entry is an all-addresses network (prefix length 0), e.g. 0.0.0.0/0 or ::/0.</summary>
    private static bool IsAllAddresses(string entry)
    {
        var value = (entry ?? string.Empty).Trim();
        var slash = value.IndexOf('/');
        if (slash < 0) return false;
        var prefixPart = value[(slash + 1)..];
        return int.TryParse(prefixPart, out var prefix)
               && prefix == 0
               && IPAddress.TryParse(value[..slash], out _);
    }

    private static void ValidateCidrOrIp(string projectId, string entry)
    {
        var value = (entry ?? string.Empty).Trim();
        if (value.Length == 0) throw new ArgumentException($"Project '{projectId}' has an empty IP/CIDR entry.");

        // Accept either a bare address (allow 1.2.3.4;) or a CIDR network (allow 10.0.0.0/8;).
        // nginx accepts CIDRs with host bits set (e.g. allow 10.0.0.5/24;), so validate the
        // address and prefix separately rather than via IPNetwork.TryParse (which rejects them).
        if (value.Contains('/'))
        {
            var slash = value.IndexOf('/');
            var addressPart = value[..slash];
            var prefixPart = value[(slash + 1)..];

            if (!IPAddress.TryParse(addressPart, out var address))
            {
                throw new ArgumentException($"Project '{projectId}': invalid CIDR '{value}' (bad address).");
            }

            var maxPrefix = address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetworkV6 ? 128 : 32;
            if (!int.TryParse(prefixPart, out var prefix) || prefix < 0 || prefix > maxPrefix)
            {
                throw new ArgumentException($"Project '{projectId}': invalid CIDR '{value}' (prefix must be 0-{maxPrefix}).");
            }
        }
        else if (!IPAddress.TryParse(value, out _))
        {
            throw new ArgumentException($"Project '{projectId}': invalid IP address '{value}'.");
        }
    }
}
