using System.Net;
using System.Text;
using System.Text.RegularExpressions;

namespace UeDtLauncher;

/// <summary>
/// Server-side per-project IP allowlist. Kept as a separate server-only file (NOT in the
/// client-facing catalog) because it is infrastructure access-control data.
/// Shape: { "projects": { "&lt;projectId&gt;": ["10.10.20.0/24", "172.18.45.7", ...] } }
/// </summary>
public sealed class ProjectIpAllowlist
{
    public Dictionary<string, List<string>> Projects { get; set; } = new();
}

/// <summary>
/// Turns a <see cref="ProjectIpAllowlist"/> into nginx per-project <c>location</c> blocks that
/// allow only the listed IPs/CIDRs and deny everyone else. nginx is the only real enforcement
/// point (the launcher runs on the client and can be bypassed).
/// </summary>
public static class NginxAclGenerator
{
    public static string Generate(ProjectIpAllowlist allowlist)
    {
        if (allowlist.Projects.Count == 0) throw new ArgumentException("Allowlist has no projects.");

        var sb = new StringBuilder();
        sb.AppendLine("# AUTO-GENERATED by 'UeDtLauncher generate-nginx-acl'. Do not edit by hand.");
        sb.AppendLine("# Per-project IP allowlist. INCLUDE THIS ABOVE the generic /projects/ location blocks");
        sb.AppendLine("# in your server { } block — nginx uses the FIRST matching regex location, so this");
        sb.AppendLine("# must come before  location ~ ^/projects/[^/]+/...  to take effect.");
        sb.AppendLine("# Each block gates the ENTIRE project path (prod + dev) to the listed IPs/CIDRs.");

        foreach (var (projectId, entries) in allowlist.Projects)
        {
            if (string.IsNullOrWhiteSpace(projectId)) throw new ArgumentException("Allowlist contains an empty projectId.");
            if (entries is null || entries.Count == 0) throw new ArgumentException($"Project '{projectId}' has no allowed IPs/CIDRs.");

            sb.AppendLine();
            sb.AppendLine($"location ~ ^/projects/{Regex.Escape(projectId)}/ {{");
            foreach (var entry in entries)
            {
                ValidateCidrOrIp(projectId, entry);
                sb.AppendLine($"    allow {entry.Trim()};");
            }
            sb.AppendLine("    deny all;");
            sb.AppendLine("    try_files $uri =404;");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void ValidateCidrOrIp(string projectId, string entry)
    {
        var value = (entry ?? string.Empty).Trim();
        if (value.Length == 0) throw new ArgumentException($"Project '{projectId}' has an empty IP/CIDR entry.");

        // Accept either a bare address (allow 1.2.3.4;) or a CIDR network (allow 10.0.0.0/8;).
        if (value.Contains('/'))
        {
            if (!IPNetwork.TryParse(value, out _)) throw new ArgumentException($"Project '{projectId}': invalid CIDR '{value}'.");
        }
        else if (!IPAddress.TryParse(value, out _))
        {
            throw new ArgumentException($"Project '{projectId}': invalid IP address '{value}'.");
        }
    }
}
