<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>UeDtLauncher.TestServer</AssemblyName>
    <RootNamespace>UeDtLauncher.TestServer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\UeDtLauncher.Core\UeDtLauncher.Core.csproj" />
  </ItemGroup>
</Project>
